### ISSUE TITLE
C++:Linking error while compiling this test code

### ISSUE THREAD

**Issue by Kunyadav** [rcorredorj/elastix-cpp-test#1]
Hi rcorredorj,
 I have built elastix 5.1.0 and ITK 5.3.0 with x64 visual studio2017 native tool and then trying to compile the sample test code using x64 visual studio 2017 . i am getting below linking error , could you please help me in resolving these error?

Regards
Kunal

**ERRORs:**

elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FixedGenericPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class elast
ix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FixedRecursivePyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class ela
stix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FixedShrinkingPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class ela
stix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FixedSmoothingPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class ela
stix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FullSamplerInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Comp
onentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol GridSamplerInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Comp
onentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MultiInputRandomCoordinateSamplerInstallComponent referenced in function "int __cdecl InstallAllComponen
ts(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RandomSamplerInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Co
mponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RandomCoordinateSamplerInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RandomSamplerSparseMaskInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol BSplineInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(class elast
ix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol BSplineInterpolatorFloatInstallComponent referenced in function "int __cdecl InstallAllComponents(class
elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol LinearInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(class elasti
x::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol NearestNeighborInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(cla
ss elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RayCastInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(class elast
ix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol ReducedDimensionBSplineInterpolatorInstallComponent referenced in function "int __cdecl InstallAllCompon
ents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedKappaStatisticMetricInstallComponent referenced in function "int __cdecl InstallAllComponents(cl
ass elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedMattesMutualInformationMetricInstallComponent referenced in function "int __cdecl InstallAllComp
onents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedMeanSquaresMetricInstallComponent referenced in function "int __cdecl InstallAllComponents(class
 elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedNormalizedCorrelationMetricInstallComponent referenced in function "int __cdecl InstallAllCompon
ents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol TransformBendingEnergyPenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(c
lass elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol CorrespondingPointsEuclideanDistanceMetricInstallComponent referenced in function "int __cdecl InstallAl
lComponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol DisplacementMagnitudePenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(cl
ass elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol DistancePreservingRigidityPenaltyInstallComponent referenced in function "int __cdecl InstallAllComponen
ts(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol GradientDifferenceMetricInstallComponent referenced in function "int __cdecl InstallAllComponents(class
elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol KNNGraphAlphaMutualInformationMetricInstallComponent referenced in function "int __cdecl InstallAllCompo
nents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MissingStructurePenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol NormalizedGradientCorrelationMetricInstallComponent referenced in function "int __cdecl InstallAllCompon
ents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol NormalizedMutualInformationMetricInstallComponent referenced in function "int __cdecl InstallAllComponen
ts(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PCAMetricInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Compon
entDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PCAMetric2InstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Compo
nentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PatternIntensityMetricInstallComponent referenced in function "int __cdecl InstallAllComponents(class el
astix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PolydataDummyPenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(class elas
tix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol TransformRigidityPenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(class
elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol StatisticalShapePenaltyInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol SumOfPairwiseCorrelationCoefficientsMetricInstallComponent referenced in function "int __cdecl InstallAl
lComponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol SumSquaredTissueVolumeDifferenceMetricInstallComponent referenced in function "int __cdecl InstallAllCom
ponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol VarianceOverLastDimensionMetricInstallComponent referenced in function "int __cdecl InstallAllComponents
(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MovingGenericPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class elas
tix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MovingRecursivePyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class el
astix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MovingShrinkingPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class el
astix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MovingSmoothingPyramidInstallComponent referenced in function "int __cdecl InstallAllComponents(class el
astix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdaptiveStochasticGradientDescentInstallComponent referenced in function "int __cdecl InstallAllComponen
ts(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol CMAEvolutionStrategyInstallComponent referenced in function "int __cdecl InstallAllComponents(class elas
tix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol ConjugateGradientInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix
::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol ConjugateGradientFRPRInstallComponent referenced in function "int __cdecl InstallAllComponents(class ela
stix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FiniteDifferenceGradientDescentInstallComponent referenced in function "int __cdecl InstallAllComponents
(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol FullSearchInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Compo
nentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PowellInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Component
Database *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol PreconditionedStochasticGradientDescentInstallComponent referenced in function "int __cdecl InstallAllCo
mponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol QuasiNewtonLBFGSInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix:
:ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RSGDEachParameterApartInstallComponent referenced in function "int __cdecl InstallAllComponents(class el
astix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RegularStepGradientDescentInstallComponent referenced in function "int __cdecl InstallAllComponents(clas
s elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol SimplexInstallComponent referenced in function "int __cdecl InstallAllComponents(class elastix::Componen
tDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol SimultaneousPerturbationInstallComponent referenced in function "int __cdecl InstallAllComponents(class
elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol StandardGradientDescentInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MultiMetricMultiResolutionRegistrationInstallComponent referenced in function "int __cdecl InstallAllCom
ponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MultiResolutionRegistrationInstallComponent referenced in function "int __cdecl InstallAllComponents(cla
ss elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MultiResolutionRegistrationWithFeaturesInstallComponent referenced in function "int __cdecl InstallAllCo
mponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol BSplineResampleInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(cla
ss elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol BSplineResampleInterpolatorFloatInstallComponent referenced in function "int __cdecl InstallAllComponent
s(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol LinearResampleInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(clas
s elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol NearestNeighborResampleInterpolatorInstallComponent referenced in function "int __cdecl InstallAllCompon
ents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol ReducedDimensionBSplineResampleInterpolatorInstallComponent referenced in function "int __cdecl InstallA
llComponents(class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol RayCastResampleInterpolatorInstallComponent referenced in function "int __cdecl InstallAllComponents(cla
ss elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol MyStandardResamplerInstallComponent referenced in function "int __cdecl InstallAllComponents(class elast
ix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedAffineTransformElastixInstallComponent referenced in function "int __cdecl InstallAllComponents(
class elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AdvancedBSplineTransformInstallComponent referenced in function "int __cdecl InstallAllComponents(class
elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AffineDTITransformElastixInstallComponent referenced in function "int __cdecl InstallAllComponents(class
 elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AffineLogStackTransformInstallComponent referenced in function "int __cdecl InstallAllComponents(class e
lastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol AffineLogTransformElastixInstallComponent referenced in function "int __cdecl InstallAllComponents(class
 elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol BSplineStackTransformInstallComponent referenced in function "int __cdecl InstallAllComponents(class ela
stix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol DeformationFieldTransformInstallComponent referenced in function "int __cdecl InstallAllComponents(class
 elastix::ComponentDatabase *)" (?InstallAllComponents@@YAHPEAVComponentDatabase@elastix@@@Z) [F:\elast\sample\build\ElastixProxyApp.vcxproj]
elastix-5.1.lib(elxComponentLoader.obj) : error LNK2019: unresolved external symbol EulerStackTransformInstallComponent referenced in fu

**Comment by rcorredorj** [comment]
Hi Kunal,

I saw that you also write in the elastix group which is the good way to go. Unfortunately, I cannot help you much with this because I did the tests with ITK 4.11 and I know that there are changes in ITK 5. I can very much imagine that is just a proper verification of versions and setting the dependencies in VS. I cannot promise that I may have the time to test this, but if I had a little chance, I will let you know.

All the best ! 

RaC
